### PR TITLE
feat: use original fonts from old log design on new log design

### PR DESCRIPTION
**Pull request by ktwbc**
Use Helvetica fonts on new log format, with some minor padding tweaks to make the new format more readable. Also removed Jetbrains .idea folder and added to .gitignore.

Additional commits, made the Change Font into a checkbox option on the popup box so it can be optional. Also removed some unused code.

### CODE REVIEW

**Comment by ilhan-mstf** [comment]
Thank you for your contribution, I'll check it tomorrow

**Comment by ktwbc** [comment]
I updated this PR and made the font a checkbox on the panel along with some cleanup refactoring.

**Comment by ktwbc** [comment]
The old interface is being turned off tomorrow. Just following up on the PR.

**Review by ilhan-mstf — APPROVED** [review]

**Comment by ilhan-mstf** [comment]
Thank you @ktwbc

**Comment by ilhan-mstf** [comment]
I've just submitted to review @ktwbc
It may take a couple days to be published. Once it is published can you check the changes?

**Comment by ktwbc** [comment]
Yes, no problem.

**Comment by ktwbc** [comment]
It published this morning and works.
K

**Pull request merged**
